
[colors]
background = #000000
#1E2127
background-alt = #373B41
foreground = #ffffff
#C5C8C6
primary = #41A55D
#41A55D
#61AFEF
#0780D7
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = 
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMonoNL NF ;3

modules-left = logos xworkspaces xwindow
modules-center = date
modules-right = cpu memory  pulseaudio battery wlan eth systray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
 wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt


[module/logos]
type = custom/text
content = "󰌽 Linux Mint+i3wm "
content-padding = 1

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
#type = internal/xwindow
#label =  %{F#61AFEF} %{F#ffffff}%title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted =󰝟 muted
label-muted-foreground = ${colors.disabled}

# Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
# Default: true
use-ui-max = false

# Interval for volume increase/decrease (in percent points)
# Default: 5
interval = 5

[module/xkeyboard]
type = internal/xkeyboard
#blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.primary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = ":"
format-prefix-foreground = ${colors.primary}
label = Used:%percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#41A55D} %{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected =%{F#41A55D}  %{F-}%essid%
#%{F#F0C674}%ifname%%{F-} %essid% 
# %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#41A55D}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date =%{F#41A55D}󰥔 %{F#FFFFFF}%I:%M %p
date-alt =%{F#41A55D}󰥔 %{F#FFFFFF}%Y-%m-%d %I:%M:%S %p

label = %date%
label-foreground = #27D64B

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini

[module/battery]
type = internal/battery
full-at = 100
battery = BAT0
adapter = ADP0

poll-interval = 2

; Charging
format-charging = <label-charging>
label-charging = %{F#41A55D} %{F#FFFFFF}%percentage%%

; Discharging
format-discharging = <label-discharging>
label-discharging = %{F#41A55D} %{F#FFFFFF}%percentage%%

; Low battery
label-low = %{F#FF0000} %percentage%%
format-low = <label-low>
low-at = 20
